export const surpriseMePrompts = [
  'an armchair in the shape of an avocado',
  'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
  'teddy bears shopping for groceries in Japan, ukiyo-e',
  'an oil painting by Matisse of a humanoid robot playing chess',
  'panda mad scientist mixing sparkling chemicals, digital art',
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
  'an astronaut lounging in a tropical resort in space, vaporwave',
  'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
  'a stained glass window depicting a hamburger and french fries',
  'a pencil and watercolor drawing of a bright city in the future with flying cars',
  'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
  'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  'an oil pastel drawing of an annoyed cat in a spaceship',
  'a painting of a fox in the style of Starry Night',
  'a bowl of soup that looks like a monster, knitted out of wool',
  'A plush toy robot sitting against a yellow wall',
  'A synthwave style sunset above the reflecting water of the sea, digital art',
  'Two futuristic towers with a skybridge covered in lush foliage, digital art',
  'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
  'A comic book cover of a superhero wearing headphones',
  'A centered explosion of colorful powder on a black background',
  'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
  'A photo of a white fur monster standing in a purple room',
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  'A Samurai riding a Horse on Mars, lomography.',
  'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
  'A realistic photograph of a young woman with blue eyes and blonde hair',
  'A man standing in front of a stargate to another dimension',
  'Spongebob Squarepants in the Blair Witch Project',
  'A velociraptor working at a hotdog stand, lomography',
  'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
  'A BBQ that is alive, in the style of a Pixar animated movie',
  'A futuristic cyborg dance club, neon lights',
  'The long-lost Star Wars 1990 Japanese Anime',
  'A hamburger in the shape of a Rubik’s cube, professional food photography',
  'A Synthwave Hedgehog, Blade Runner Cyberpunk',
  'An astronaut encountering an alien life form on a distant planet, photography',
  'A Dinosaur exploring Cape Town, photography',
  'A Man falling in Love with his Computer, digital art',
  'A photograph of a cyborg exploring Tokyo at night, lomography',
  'Dracula walking down the street of New York City in the 1920s, black and white photography',
  'Synthwave aeroplane',
  'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
  'A Space Shuttle flying above Cape Town, digital art',
  'A majestic dragon soaring through a celestial storm, its scales shimmering with lightning',
  'A futuristic cityscape with holographic billboards and flying cars in a neon-lit night',
  'An enchanted forest with glowing mushrooms, where fairies dance under a starry sky',
  'A surreal underwater world where jellyfish swim amidst colorful coral reefs and sunken ships',
  'A time-lapse image of a flower blooming, its petals unfurling with vibrant colors',
  'A robotic orchestra performing on a stage, each member playing an instrument made of gears',
  'An abstract representation of sound waves merging with vibrant, swirling colors',
  'A peaceful countryside scene with rolling hills, grazing sheep, and a vibrant rainbow',
  'A mysterious doorway leading to a hidden garden filled with floating lanterns',
  'A futuristic cityscape with sleek, transparent buildings and flying hoverboards',
  'An ethereal moonlit forest with trees that emit a soft, glowing light',
  'A cosmic collision of stars and galaxies, creating an explosion of vibrant colors',
  'A surreal underwater world where bioluminescent creatures illuminate the depths',
  'A steampunk-inspired airship sailing through the clouds, propelled by giant propellers',
  'A serene mountain landscape with cascading waterfalls and a tranquil, reflective lake',
  'An ancient temple adorned with intricate, ornamental carvings, bathed in golden sunlight',
  'A whimsical carousel populated with mythical creatures like unicorns and griffins',
  'A futuristic cityscape where towering skyscrapers are intertwined with colossal trees',
  'A serene beach at sunset, with gentle waves, seashells, and a vibrant orange sky',
  'An alien planet with floating islands, bioluminescent flora, and peculiar creatures',
  'A surreal dreamscape where gravity is defied, and objects float freely in mid-air',
  'A hidden library with shelves stretching into infinity and books glowing with magical light',
  'A vast, lush rainforest teeming with exotic wildlife and vibrant tropical flowers',
  'A surreal desert landscape with sand dunes shaped like giant waves frozen in time',
  'A fantastical underwater city inhabited by merfolk, illuminated by bioluminescent sea creatures',
  'A celestial dance of planets and stars, swirling and interweaving in a cosmic ballet',
  'A mystical doorway hidden within a towering waterfall, leading to a realm of enchantment',
  'A vibrant floating market in the clouds, where airships and floating platforms sell exotic goods',
  'A surreal forest where trees are giant mushrooms, casting an otherworldly glow on the surroundings',
  'An ancient, overgrown temple nestled within a lush jungle, holding secrets of a lost civilization',
  'A futuristic cityscape with holographic art installations that come to life through augmented reality',
  'A time-traveling adventure through a series of doorways, each leading to a different historical era',
  'A steampunk-inspired underwater laboratory, filled with intricate machinery and mechanical sea creatures',
  'A cosmic symphony of swirling galaxies and nebulae, creating harmonious patterns in the night sky',
  'A surreal garden where oversized flowers bloom, their petals unfurling into mesmerizing patterns',
  'A floating island paradise with waterfalls cascading into the sky and lush vegetation',
  'A magical library where books come to life, filling the air with tales and knowledge',
  'A futuristic metropolis where transportation is via levitating platforms and energy beams',
  'A dreamlike journey through a tunnel of swirling colors, leading to a realm of imagination',
  'A mystical night sky filled with constellations that form intricate illustrations and stories',
  'A whimsical circus filled with acrobats, fire-breathers, and animals performing fantastical feats',
  'A hidden cave adorned with glowing crystals, revealing a mesmerizing display of colors',
  'A vast desert landscape with sand dunes shaped like enormous sculptures and shifting patterns',
  'A futuristic garden with sentient robotic plants that interact and communicate with visitors'
];

export const bgColors = [
  'slate',
  'gray',
  'zinc',
  'neutral',
  'stone',
  'red',
  'orange',
  'amber',
  'yellow',
  'lime',
  'green',
  'emerald',
  'teal',
  'cyan',
  'sky',
  'blue',
  'indigo',
  'violet',
  'purple',
  'fuchsia',
  'pink',
  'rose'
];
